export enum AuthErrorCode {
  KAKAO_LOGIN_ERROR = 'KAKAO_LOGIN_ERROR',
  KAKAO_USER_NOT_FOUND = 'KAKAO_USER_NOT_FOUND',
  MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND',
  MEMBER_CONFLICT = 'MEMBER_CONFLICT',
  INVALID_IDENTIFIER = 'INVALID_IDENTIFIER',
  INVALID_LOGIN_PLATFORM = 'INVALID_LOGIN_PLATFORM',
}
