import { ReactNode } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "@/styles/global.css";

import QueryProvider from "@/lib/providers/QueryProvider";

import { LoginModalProvider } from "@/domains/auth/providers/LoginModalProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <body className={`min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <QueryProvider>
          <LoginModalProvider>{children}</LoginModalProvider>
        </QueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
